config/routes.rb
Rails.application.routes.draw do
  root "companies#index"

  resources :companies do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :tasks, dependent: :destroy

	validates :name, presence: true
	validates :note, presence: true, length: { minimum: 5 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to @company
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def company_params
      params.require(:company).permit(:name, :note, :status)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
	@company = Company.find(params[:company_id])
	@task = @company.tasks.create(task_params)
	redirect_to company_path(@company)
  end

  def destroy
	@company = Company.find(params[:company_id])
	@task = @company.tasks.find(params[:id])
	@task.destroy
	redirect_to company_path(@company), status: 303
  end
  private
	def task_params
	  params.require(:task).permit(:subject, :note, :status)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/companies/_form.html.erb
<%= form_with model: @company do |form| %>
  <div>
	<%= form.label :name, "Company Name" %><br>
	<%= form.text_field :name, class: "uk-input" %>
	<% @company.errors.full_messages_for(:name).each do |message| %>
	  <div><%= message %></div>
	<% end %>
  </div>

  <div class="uk-margin-top">
	<%= form.label :note %><br>
	<%= form.text_area :note, class: "uk-textarea" %><br>
	<% @company.errors.full_messages_for(:note).each do |message| %>
	  <div><%= message %></div>
	<% end %>
  </div>

  <div>
	<%= form.submit class: "uk-button uk-button-default uk-margin-top" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit Application Company</h1>

<%= render "form", company: @company %>

app/views/companies/index.html.erb
<h1>Applied To:</h1>

<table class="uk-table uk-table-striped uk-table-middle">
<thead>
	<tr>
		<th class="uk-padding-left">Company</th>
		<th>Note</th>
		<th>Action</th>
	</tr>
</thead>
<tbody>
  <% @companies.each do |company| %>
	<tr>
		<td><%= link_to company.name, company %></td>
		<td><%= company.note[0..50] %>...</td>
		<td>
			<%= link_to "", company,
				class:"uk-icon-button uk-button-primary",
				"uk-icon":"search"
			%>
			<%= link_to "",  edit_company_path(company),
				class: "uk-icon-button uk-button-danger",
				"uk-icon":"pencil"
			%>
		</td>
	</tr>
  <% end %>
</tbody>
</table>


<%= link_to "New Application", new_company_path, class: "uk-button uk-button-primary" %>

app/views/companies/new.html.erb
<h1>New Application</h1>

<%= render "form", company: @company %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>

<p><%= raw Anchored::Linker.auto_link( @company.note ) %></p>

<div class="">

<%= link_to "",  edit_company_path(@company),
	class: "uk-icon-button uk-button-primary",
	"uk-icon":"pencil"
%>
</div>
<hr>
<table class="uk-table uk-table-hover">
	<thead>
		<tr>
			<td>Subject</td>
			<td>Descrirption</td>
		</tr>
	</thead>
	<tbody>
	<%= render @company.tasks %>
	</tbody>
</table>

<h4>Add a Task:</h4>
<%= render 'tasks/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playground</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="uk-navbar-container uk-margin uk-margin-remove-bottom" uk-navbar>
        <div class="uk-navbar-center">

            <div class="uk-navbar-center-left"><div>
                <ul class="uk-navbar-nav">
                    <li><a href="/">All</a></li>
                </ul>
            </div></div>
            <a class="uk-navbar-item uk-logo" href="/">Application Tracker</a>
            <div class="uk-navbar-center-right"><div>
                <ul class="uk-navbar-nav">
                    <li><%= link_to "New", new_company_path %>
                      </li>
                </ul>
            </div></div>

        </div>
    </nav>
    <div class="uk-section uk-section-primary">
        <div class="uk-container uk-container-xsmall">
          <%= yield %>
        </div>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: [ @company, @company.tasks.build ] do |form| %>
  <div>
	  <%= form.label :subject %><br>
	  <%= form.text_field :subject,  class: "uk-input uk-form-width-large" %>
  </div>
  <div class="uk-margin-top">
	  <%= form.label :note, "Description" %><br>
	  <%= form.text_area :note, class: "uk-textarea uk-form-width-large" %>
  </div>
  <div>
    <%= form.submit  class: "uk-button uk-button-default uk-margin-top"%>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr>
	<td><%= task.subject %></td>
	<td><%= task.note %></td>
</tr>